POST http://localhost:4000/ads
Content-Type: application/json
{
  "title": "macbook3",
  "price": 1300,
  "location": "Strasbourg",
  "pictureUrl": "https://media.ldlc.com/r1600/ld/products/00/04/41/75/LD0004417599_2.jpg"
}