POST http://127.0.0.1:4000/ads/

Content-Type: application/json
{
  "titre": "macbook3",
  "prix": 1300,
  "location": "Strasbourg",
  "picpath": "https://media.ldlc.com/r1600/ld/products/00/04/41/75/LD0004417599_2.jpg",
  "category": {"id": 1},
  "tags": [{"id": 1}, {"id": 2}]
}